name: my-pantheon-site
recipe: pantheon
config:
  framework: drupal8
  site: my-pantheon-site
  id: 1
  xdebug: true
  drush: global:8.1.16
proxy:
  nginx:
    - mypan.lndo.site

services:

  # Override the appserver with composer globals, build step and custom php.ini
  # See: https://docs.devwithlando.io/services/php.html
  appserver:
    run_as_root:
      - "apt-get update -y"
      - "apt-get install vim -y"
      - "apt-get install build-essential chrpath libssl-dev libxft-dev libfreetype6-dev libfreetype6 libfontconfig1-dev libfontconfig1 libicu-dev imagemagick ruby-full nodejs npm rake -y"
      - "npm install -g casperjs"
      - "gem install wraith"
#      - "cd /app && wraith setup"
      - "wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2"
      - "tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2 -C /usr/local/share/"
      - "ln -s /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/"


# Add a php unit command and node commands
# See: https://docs.devwithlando.io/config/tooling.html
tooling:
  phantomjs:
    service: appserver
    description: "Run phantomjs commands"
  vim:
    service: appserver
  npm:
    service: appserver
    description: "Run npm commands"
  nodejs:
    service: appserver
    description: "Run node commands"
  gem:
    service: appserver
    description: "Run gem commands"
  ruby:
    service: appserver
    description: "Run ruby commands"
  wraith:
    service: appserver
    description: "Run wraith commands"
