name: my-pantheon-site
recipe: pantheon
config:
  framework: drupal8
  site: my-panthoen-site
  id: 2
  xdebug: true
  drush: global:8.1.16
proxy:
  nginx:
    - mypan.lndo.site

services:
  ruby:
    type: ruby
    overrides:
      services:
        image: bbcnews/wraith

tooling:
  npm:
    service: ruby
  node:
    service: ruby
  wraith:
    service: ruby
  ruby:
    service: ruby
  gem:
    service: ruby
